<div class="btn-div"><input type="submit"  value="A" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="B" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="C" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="D" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="E" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="F" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="G" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="H" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="I" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="J" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="K" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="L" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="M" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="N" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="O" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="P" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="Q" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="R" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="S" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="T" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="U" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="V" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="W" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="X" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="Y" name="lettersrch" class="nice-btn btn primary"/></div>
<div class="btn-div"><input type="submit"  value="Z" name="lettersrch" class="nice-btn btn primary"/></div>